[metadata]
name = ironic-wakeup-plugin
summary = "Ironic plugin for Redfish and IPMI Wakeup hardware types"
version = 0.0.1

[options]
packages = find:
install_requires =
    ironic>=32.0.0  # Adjust to your minimum required version

[entry_points]
ironic.hardware.interfaces.boot =
    redfish-wakeup = ironic_wakeup_plugin.boot:SSHWakeup
    ipmi-wakeup = ironic_wakeup_plugin.boot:SSHWakeup

ironic.hardware.types =
    redfish-wakeup = ironic_wakeup_plugin.redfish_wakeup:RedfishWakeupHardware
    ipmi-wakeup = ironic_wakeup_plugin.ipmi_wakeup:IPMIWakeupHardware
